name: example-environment
channels:
  - conda-forge
dependencies:
  - cython>=0.29.20, <3.0.0
  - scipy
  - numpy
  - qutip
  - matplotlib
  - h5py>=2.7.1
  - tqdm
  - cycler
  - pathos
  - dill
  - scqubits==3.2
  - sympy
  - ipyvuetify
